# Enginsight Enterprise Helm Chart Values

# -- Override the name of the chart
nameOverride: ""
# -- Override the full name of the chart
fullnameOverride: ""

# Enginsight-specific image configuration
images:
  # -- Image registry for Enginsight services
  registry: registry.enginsight.com
  # -- List of image pull secrets for accessing private registry
  imagePullSecrets:
    - name: enginsight-registry-secret

# Individual service configurations
services:
  #  UI Frontend Service (ui-m1) configuration
  ui:
    # -- Enable or disable the UI service
    enabled: true
    #  UI service image configuration
    image:
      # -- UI service image repository
      repository: registry.enginsight.com/enginsight/ui-m1
      # -- UI service image tag
      tag: "7.7.4"
      # -- UI service image pull policy
      pullPolicy: IfNotPresent
    # -- Number of UI service replicas
    replicaCount: 1
    # -- UI service port
    port: 80
    #  UI service ingress configuration
    ingress:
      # -- Enable ingress for UI service
      enabled: true
      # -- Ingress class name
      className: traefik
      # -- Ingress annotations
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http01-prod
      # -- Ingress hosts configuration
      hosts:
        - host: ui-enginsight.188-245-122-8.nip.io
          paths:
            - path: /
              pathType: ImplementationSpecific
      # -- TLS configuration for ingress
      tls:
        - secretName: ui-enginsight-tls
          hosts:
            - ui-enginsight.188-245-122-8.nip.io
    # -- Additional labels for UI service pods
    podLabels: {}
    # -- Additional annotations for UI service pods
    podAnnotations: {}
    # -- Node selector for UI service pods
    nodeSelector: {}
    # -- Tolerations for UI service pods
    tolerations: []
    # -- Affinity rules for UI service pods
    affinity: {}
    # -- Resource limits and requests for UI service
    resources: {}
    # resources:
    #   limits:
    #     cpu: 100m
    #     memory: 128Mi
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    # -- Pod Security Context
    podSecurityContext: {}
    # podSecurityContext:
    #   runAsNonRoot: true
    #   runAsUser: 101
    #   runAsGroup: 101
    #   fsGroup: 101
    # -- Container Security Context
    securityContext: {}
    # securityContext:
    #   allowPrivilegeEscalation: false
    #   capabilities:
    #     drop:
    #       - ALL
    #     add:
    #       - NET_BIND_SERVICE
    #   readOnlyRootFilesystem: true
    # -- livenessProbe
    # livenessProbe:
    #   httpGet:
    #     path: /
    #     port: 80
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    # -- readinessProbe
    # readinessProbe:
    #   httpGet:
    #     path: /
    #     port: 80
    #   initialDelaySeconds: 5
    #   periodSeconds: 5

  # API Server Service (server-m2)
  server:
    enabled: true
    image:
      repository: registry.enginsight.com/enginsight/server-m2
      tag: "7.7.4"
      pullPolicy: IfNotPresent
    replicaCount: 1
    port: 8080
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http01-prod
      hosts:
        - host: api-enginsight.188-245-122-8.nip.io
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: api-enginsight-tls
          hosts:
            - api-enginsight.188-245-122-8.nip.io
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    # podSecurityContext:
    #   runAsNonRoot: true
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    securityContext: {}
    # securityContext:
    #   allowPrivilegeEscalation: false
    #   capabilities:
    #     drop:
    #       - ALL
    #   readOnlyRootFilesystem: false
    resources: {}
    # resources:
    #   limits:
    #     cpu: 100m
    #     memory: 128Mi
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    # livenessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    # readinessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 5
    #   periodSeconds: 5

  # -- Anomalies detection service (anomalies-m28)
  anomalies:
    enabled: true
    image:
      repository: registry.enginsight.com/enginsight/anomalies-m28
      tag: "2.3.0"
    replicaCount: 1
    port: 8080
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    # podSecurityContext:
    #   runAsNonRoot: true
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    securityContext: {}
    # securityContext:
    #   allowPrivilegeEscalation: false
    #   capabilities:
    #     drop:
    #       - ALL
    #   readOnlyRootFilesystem: false
    resources: {}
    # resources:
    #   limits:
    #     cpu: 100m
    #     memory: 128Mi
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    # livenessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    # readinessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 5
    #   periodSeconds: 5

  # -- Data generator service (generator-m35)
  generator:
    enabled: true
    image:
      repository: registry.enginsight.com/enginsight/generator-m35
      tag: "1.15.34"
    replicaCount: 1
    port: 8080
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    # podSecurityContext:
    #   runAsNonRoot: true
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    securityContext: {}
    # securityContext:
    #   allowPrivilegeEscalation: false
    #   capabilities:
    #     drop:
    #       - ALL
    #   readOnlyRootFilesystem: false
    resources: {}
    # resources:
    #   limits:
    #     cpu: 100m
    #     memory: 128Mi
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    # livenessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    # readinessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 5
    #   periodSeconds: 5

  # -- Historical data service (historian-m38)
  historian:
    enabled: true
    image:
      repository: registry.enginsight.com/enginsight/historian-m38
      tag: "2.3.8"
    replicaCount: 1
    port: 8080
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    # podSecurityContext:
    #   runAsNonRoot: true
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    securityContext: {}
    # securityContext:
    #   allowPrivilegeEscalation: false
    #   capabilities:
    #     drop:
    #       - ALL
    #   readOnlyRootFilesystem: false
    resources: {}
    # resources:
    #   limits:
    #     cpu: 100m
    #     memory: 128Mi
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    # livenessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    # readinessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 5
    #   periodSeconds: 5

  # -- Profiler service (profiler-m22)
  profiler:
    enabled: true
    image:
      repository: registry.enginsight.com/enginsight/profiler-m22
      tag: "2.2.17"
    replicaCount: 1
    port: 8080
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    # podSecurityContext:
    #   runAsNonRoot: true
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    securityContext: {}
    # securityContext:
    #   allowPrivilegeEscalation: false
    #   capabilities:
    #     drop:
    #       - ALL
    #   readOnlyRootFilesystem: false
    resources: {}
    # resources:
    #   limits:
    #     cpu: 100m
    #     memory: 128Mi
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    # livenessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    # readinessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 5
    #   periodSeconds: 5

  # -- Reporter service (reporter-m4)
  reporter:
    enabled: true
    image:
      repository: registry.enginsight.com/enginsight/reporter-m4
      tag: "3.2.4"
    replicaCount: 1
    port: 8080
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    # podSecurityContext:
    #   runAsNonRoot: true
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    securityContext: {}
    # securityContext:
    #   allowPrivilegeEscalation: false
    #   capabilities:
    #     drop:
    #       - ALL
    #   readOnlyRootFilesystem: false
    resources: {}
    # resources:
    #   limits:
    #     cpu: 100m
    #     memory: 128Mi
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    # livenessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    # readinessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 5
    #   periodSeconds: 5

  # -- Scheduler service (scheduler-m29)
  scheduler:
    enabled: true
    image:
      repository: registry.enginsight.com/enginsight/scheduler-m29
      tag: "1.12.8"
    replicaCount: 1
    port: 8080
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    # podSecurityContext:
    #   runAsNonRoot: true
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    securityContext: {}
    # securityContext:
    #   allowPrivilegeEscalation: false
    #   capabilities:
    #     drop:
    #       - ALL
    #   readOnlyRootFilesystem: false
    resources: {}
    # resources:
    #   limits:
    #     cpu: 100m
    #     memory: 128Mi
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    # livenessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    # readinessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 5
    #   periodSeconds: 5

  # -- Sentinel monitoring service (sentinel-m3)
  sentinel:
    enabled: true
    image:
      repository: registry.enginsight.com/enginsight/sentinel-m3
      tag: "2.27.29"
    replicaCount: 1
    port: 8080
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    # podSecurityContext:
    #   runAsNonRoot: true
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    securityContext: {}
    # securityContext:
    #   allowPrivilegeEscalation: false
    #   capabilities:
    #     drop:
    #       - ALL
    #   readOnlyRootFilesystem: false
    resources: {}
    # resources:
    #   limits:
    #     cpu: 100m
    #     memory: 128Mi
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    # livenessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    # readinessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 5
    #   periodSeconds: 5

  # -- Themis governance service (themis-m43)
  themis:
    enabled: true
    image:
      repository: registry.enginsight.com/enginsight/themis-m43
      tag: "2.1.31"
    replicaCount: 1
    port: 8080
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    # podSecurityContext:
    #   runAsNonRoot: true
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    securityContext: {}
    # securityContext:
    #   allowPrivilegeEscalation: false
    #   capabilities:
    #     drop:
    #       - ALL
    #   readOnlyRootFilesystem: false
    resources: {}
    # resources:
    #   limits:
    #     cpu: 100m
    #     memory: 128Mi
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    # livenessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    # readinessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 5
    #   periodSeconds: 5

  # -- Updater service (updater-m34)
  updater:
    enabled: true
    image:
      repository: registry.enginsight.com/enginsight/updater-m34
      tag: "2.4.1"
    replicaCount: 1
    port: 8080
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    # podSecurityContext:
    #   runAsNonRoot: true
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    securityContext: {}
    # securityContext:
    #   allowPrivilegeEscalation: false
    #   capabilities:
    #     drop:
    #       - ALL
    #   readOnlyRootFilesystem: false
    resources: {}
    # resources:
    #   limits:
    #     cpu: 100m
    #     memory: 128Mi
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    # livenessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    # readinessProbe:
    #   httpGet:
    #     path: /health
    #     port: 8080
    #   initialDelaySeconds: 5
    #   periodSeconds: 5

# Configuration settings
config:
  # Services configuration (services-config Secret)
  services:
    # -- Existing Secret with config.js
    existingSecret: "enginsight-services-config"
    # kubectl -n enginsight create secret generic enginsight-services-config --from-file=config.json
    # config.json:
    # {
    #   "onpremise": {
    #     "twoFactor": {
    #       "enabled": false
    #     }
    #   },
    #   "api": {
    #     "url": "%%API_URL%%",
    #     "port": 8080,
    #     "timeout": 5000,
    #     "clientMaxBodySize": "50mb",
    #     "cookies": {
    #       "maxAge": 3600000,
    #       "domain": "",
    #       "path": "/",
    #       "signed": false
    #     },
    #     "recaptcha": {
    #       "secret": "",
    #       "host": "www.google.com",
    #       "path": "/recaptcha/api/siteverify",
    #       "method": "POST"
    #     },
    #     "headers": {},
    #     "jwt": {
    #       "secret": "%%JWT_SECRET%%",
    #       "expiresIn": "24h"
    #     }
    #   },
    #   "loopDelay": 15000,
    #   "database": {
    #     "uriConnectionString": "%%MONGODB_URI%%"
    #   },
    #   "cache": "redis-master",
    #   "email": {
    #     "sender": "'Enginsight' <no-reply@your.domain>",
    #     "host": "",
    #     "port": "",
    #     "sslTls": true,
    #     "user": "",
    #     "pass": "",
    #     "maxConnections": 2,
    #     "rateDelta": 1000,
    #     "rateLimit": 1
    #   },
    #   "integrations": {
    #     "slack": {
    #       "clientId": "",
    #       "clientSecret": ""
    #     }
    #   },
    #   "cves": {
    #     "uriConnectionString": "mongodb://mongodb-cves/cves"
    #   },
    #   "app": {
    #     "host": "%%APP_URL%%"
    #   },
    #   "sms": {
    #     "limit": 20,
    #     "region": "",
    #     "accessKeyId": "",
    #     "secretAccessKey": "",
    #     "senderId": ""
    #   }
    # }

  # -- UI configuration (ui-config ConfigMap)
  ui:
    hinting: true
    modulePrefix: "ngs-ui-m1"
    environment: "production"
    rootURL: "/"
    locationType: "auto"
    recaptchaKey: ""
    onpremise:
      version: 1

# Service Account configuration
serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use (if empty, a name is generated)
  name: ""

# Network policies configuration
networkPolicies:
  # -- Master switch for network policies - enables pod-to-pod communication isolation
  enabled: false

#  MongoDB dependency configuration - disable if external backends are being used
mongodb:
  # -- Enable MongoDB deployment as part of this chart
  enabled: true
  # -- MongoDB architecture (standalone or replicaset)
  architecture: "replicaset"
  # -- MongoDB authentication configuration
  auth:
    # -- Enable MongoDB authentication
    enabled: false
    existingSecret: ""
    rootUser: "root"
    rootPassword: ""
    usernames: []
    passwords: []
    databases: []
  arbiter:
    enabled: false
  replicaCount: 1

# MongoDB CVE database configuration - separate MongoDB instance for CVE data
mongodb-cves:
  # -- Enable MongoDB CVE database deployment
  enabled: true
  # -- MongoDB architecture for CVE database (standalone or replicaset)
  architecture: "replicaset"
  # -- MongoDB authentication configuration for CVE database
  auth:
    # -- Enable MongoDB authentication for CVE database
    enabled: false
    existingSecret: ""
    rootUser: "root"
    rootPassword: ""
    usernames: []
    passwords: []
    databases: []
  arbiter:
    enabled: false
  replicaCount: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1.5Gi"

# Redis dependency configuration for caching
redis:
  # -- Enable Redis deployment as part of this chart
  enabled: true
  # -- Redis architecture (standalone or replication)
  architecture: standalone
  # -- Redis authentication configuration
  auth:
    # -- Enable Redis authentication
    enabled: false
    existingSecret: ""
    existingSecretPasswordKey: ""
    password: ""
  master:
    persistence:
      enabled: false
