{{- if .Values.services.scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enginsight.fullname" . }}-scheduler
  labels:
    app.kubernetes.io/name: {{ include "enginsight.fullname" . }}-scheduler
    {{- range $key, $value := .Values.services.scheduler.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- include "enginsight.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.scheduler.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "enginsight.fullname" . }}-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.services.scheduler.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- if .Values.networkPolicies.enabled }}
        database-access: "mongodb"
        cache-access: "redis"
        {{- end }}
        app.kubernetes.io/name: {{ include "enginsight.fullname" . }}-scheduler
        {{- range $key, $value := .Values.services.scheduler.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- if .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.images.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "enginsight.serviceAccountName" . }}
      {{- if .Values.services.scheduler.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.services.scheduler.podSecurityContext | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      {{- with .Values.services.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: scheduler-m29
          {{- if .Values.services.scheduler.securityContext }}
          securityContext:
            {{- toYaml .Values.services.scheduler.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.images.registry }}/{{ .Values.services.scheduler.image.repository }}:{{ .Values.services.scheduler.image.tag }}"
          imagePullPolicy: {{ .Values.services.scheduler.image.pullPolicy | default "IfNotPresent" }}
          {{- if .Values.services.scheduler.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.services.scheduler.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.services.scheduler.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.services.scheduler.readinessProbe | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/enginsight/scheduler-m29/config.json
              name: services-config
              subPath: config.json
          resources:
            {{- toYaml .Values.services.scheduler.resources | nindent 12 }}
      volumes:
        - name: services-config
          configMap:
            name: {{ include "enginsight.fullname" . }}-services-config
{{- end }}