{{- if and .Values.services.ui.enabled .Values.services.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "enginsight.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: {{ include "enginsight.fullname" . }}-ui
    {{- include "enginsight.labels" . | nindent 4 }}
  {{- with .Values.services.ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.services.ui.ingress.className }}
  ingressClassName: {{ .Values.services.ui.ingress.className }}
  {{- end }}
  {{- if .Values.services.ui.ingress.tls }}
  tls:
    {{- range .Values.services.ui.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.services.ui.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "enginsight.fullname" $ }}-ui
                port:
                  number: {{ $.Values.services.ui.port }}
          {{- end }}
    {{- end }}
{{- end }}