name: Release Charts

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.1

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Update chart dependencies
        run: |
          find charts -name 'Chart.yaml' -exec helm dependency update "$(dirname {})" \;

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          HELM_EXPERIMENTAL_OCI: "1"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Charts to GHCR
        run: |
          if [ -d ".cr-release-packages" ] && [ "$(ls -A .cr-release-packages)" ]; then
            for pkg in .cr-release-packages/*; do
              if [ -f "${pkg}" ]; then
                echo "Pushing ${pkg} to OCI registry..."
                helm push "${pkg}" oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts
              fi
            done
          else
            echo "No packages found in .cr-release-packages directory"
            ls -la || echo "No .cr-release-packages directory found"
          fi