name: Renovate

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30th minute
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.9
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_USERNAME: ${{ secrets.RENOVATE_USERNAME }}
          RENOVATE_PASSWORD: ${{ secrets.RENOVATE_PASSWORD }}
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
          LOG_LEVEL: debug