name: Renovate

on:
  schedule:
    - cron: '30 8 * * *'  # Daily at 8:30 AM
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_HOST_RULES: '[{"matchHost": "registry.enginsight.com", "hostType": "docker", "username": "${{ secrets.RENOVATE_USERNAME }}", "password": "${{ secrets.RENOVATE_PASSWORD }}"}, {"matchHost": "registry-auth.enginsight.com", "hostType": "docker", "username": "${{ secrets.RENOVATE_USERNAME }}", "password": "${{ secrets.RENOVATE_PASSWORD }}"}]'
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
          LOG_LEVEL: debug